### ISSUE TITLE
Just some comments

### ISSUE THREAD

**Issue by greggman** [shrekshao/webgpu-typescript-starter#1]
Feel free to ignore

1. Don't use gl-matrix.  Why?

   1. it makes GL matrixes for perspective, ortho, and frustum. Not WebGPU matrixes
   2. it makes 3x3 matrices that are incompatible with WebGPU
  
   suggestion [wgpu-matrix](https://github.com/greggman/wgpu-matrix)

2. Don't use `window.onload`

   There's no need. That's left over from IE days AFAICT. With your script at the bottom of the content, like you have it. It will run either inline or as a function call. In other words

   ```js
   // old
   window.onload = window.onload = async () => {
     ...
   }
   ```

   ```js
   // modern
   (async() => {
     ...
   })();
   ```

   or 

   ```js
   async function main() {
     ...
   }
   main();
   ```

**Comment by shrekshao** [comment]
Thanks for the info. Good suggestions.

For the gl-matrix, I know there's [`perspectiveZO`](https://github.com/toji/gl-matrix/blob/master/src/mat4.js#L1585) made for WebGPU coordinate. Is that enough?

But yeah even so it needs an extra note to point to `perspectiveZO`. And now I know the existence of wgpu-matrix, it's better to use this more modern one.

**Comment by greggman** [comment]
> For the gl-matrix, I know there's [perspectiveZO](https://github.com/toji/gl-matrix/blob/master/src/mat4.js#L1585)

No, that doesn't cover the incompatibilities with mat3

Further, gl-matrix has a verbose API.  Compare

```js
// gl-matrix
const t = mat4.create();
mat4.fromTranslation(t, [x, y, z]);

const p = mat4.create();
mat4.perspective(p, fov, aspect, near, far);

const r = mat4.create();
mat4.fromXRotation(r, rad);
```

vs wgpu-matrix

```js
// wgpu-matrix
const t = mat4.ranslation([x, y, z]);
const p = mat4.perspective(fov, aspect, near, far);
const r = mat4.rotationX(rad);

**Comment by shrekshao** [comment]
Fixed at https://github.com/shrekshao/webgpu-typescript-starter/commit/232cc4fd2fae8c69f87bf385d5aa745ad60d0407

Thanks!
